version: '2'

services: 
        softether:
                image: siomiz/softethervpn
                env_file:
                        - softether.env
                networks:
                        local:
                                ipv4_address: 192.168.0.150

networks:
        local:
                driver: ovs
